apiVersion: v1
kind: Namespace
metadata:
  name: landflip
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: landflip
spec:
  replicas: 1
  selector:
    matchLabels: { app: api }
  template:
    metadata:
      labels: { app: api }
    spec:
      containers:
        - name: api
          image: your-registry/landflip-api:latest
          envFrom:
            - secretRef:
                name: backend-secrets
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: landflip
spec:
  selector: { app: api }
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: landflip
spec:
  replicas: 1
  selector:
    matchLabels: { app: web }
  template:
    metadata:
      labels: { app: web }
    spec:
      containers:
        - name: web
          image: your-registry/landflip-web:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: landflip
spec:
  selector: { app: web }
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
